### ISSUE TITLE
Arrow not working properly 

### ISSUE THREAD

**Issue by lemonpeu** [bryanmylee/svelte-popperjs#26]
Hi! I read a closed issue but it didn't have any solution.
The arrow is not appearing even when you add the styles BUT I found a way to show it by simply declaring: 
```

  let arrow

  const popperOptions = {
    modifiers: [
      {
        name: 'arrow',
        options: {
          element: arrow,
        },
      },
    ],
  }
```

The problem? Just by using `popperOptions` the tooltip breaks appearing far away from the text or icon or whatever you want to use as a hover. 

Here you can test it, I put a tooltip using popperOptions and the arrow appearing and the other using the styles but as you can see the arrow doesn't appear

https://codesandbox.io/s/popper-arrow-issue-r487l4

**Comment by bryanmylee** [comment]
I took a look at your repro and there are a few issues:

In the "working" example (`TooltipNoArrow`), you forgot to add `use:popperContent` to the actual tooltip div, so it's not actually being positioned with PopperJS.

If you do add `use:popperContent`, you'll notice that the popper is placed "away from the text". However, that's because the text element is actually spanning the entire width. You can observe this by adding a background color to the text element.

https://codesandbox.io/s/popper-arrow-issue-forked-x8vsd8?file=/TooltipNoArrow.svelte

When the popper content positions itself in the center of the full-width element, it appears to be off to the side.

The arrow element should work regardless.
